[package]
name = "gateway464"
version = "1.0.0"
authors = ["Lucas Fiegl <lfiegl@hellomouse.net>"]
edition = "2018"

[dependencies]
nfqueue = "0.9.1"
libc = "0.2.97"
etherparse = "0.9.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_yaml = "0.8.17"
pnet_sys = "0.28"
