[package]
name = "tinc-v4gateway"
version = "0.1.0"
authors = ["Io Void <iovoid4@gmail.com>"]
edition = "2018"

[dependencies]
nfqueue = "0.9.1"
libc = "0.2.68"
etherparse = "0.9.0"
serde = { version = "1.0.105", features = ["derive"] }
serde_yaml = "0.8.11"