base: [0x20, 0x01, 0x0D, 0xB8, 0x0, 0x00] # Base /48 for redirection
magic: [0x44, 0x41, 0x5b, 0xad] # Filler that pads the space between reverse and the encoded IP
nfqueue: 42 # NFQueue queue ID
mappings:
  1.2.3.4: # v4 address that will receive the packets
    reverse: [0x00, 0x00] # base + reverse, where the v6-ified packets will be sourced from
    ports:
      # Pair of TCP/UDP port and the address it will be sent to
      1234: "2001:db8::1"

